<?php

/**
 * @file
 * Formats multi value fields as Swiper sliders.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function field_swiper_theme($existing, $type, $theme, $path) {
  return [
    'swiper_container' => ['render element' => 'element'],
  ];
}

/**
 * Prepares variables for the swiper container.
 *
 * Default template: swiper-container.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #id, #attributes, #children.
 */
function template_preprocess_swiper_container(&$variables) {
  $element = $variables['element'];

  // Copy values into variables for easier access in template.
  $delta = 0;
  while(!empty($element['#children'][$delta])) {
    $variables['children'][$delta] = $element['#children'][$delta];
    $delta++;
  }
  $variables['label_hidden'] = ($element['#children']['#label_display'] == 'hidden');

  // Prepare attributes.
  $variables['attributes'] = new Attribute();
  $variables['title_attributes'] = new Attribute();
  $variables['container_attributes'] = new Attribute($element['#attributes']);
  $variables['wrapper_attributes'] = new Attribute(['class' => $element['#swiper_parameters']['wrapperClass']]);
  $variables['slide_attributes'] = new Attribute(['class' => $element['#swiper_parameters']['slideClass']]);

  // Check for controls and add variables for them necessary.
  $parameters = $element['#swiper_parameters'];
  $controls = [
    'pagination' => 'pagination',
    'next_button' => 'nextButton',
    'prev_button' => 'prevButton',
    'scrollbar' => 'scrollbar',
  ];
  foreach ($controls as $control => $param_key) {
    if (!empty($parameters[$param_key])) {
      $variables['controls'][$control]['attributes'] = new Attribute([
        // Replace the dot in the CSS selector string of the control.
        'class' => [str_replace('.', '', $parameters[$param_key])],
      ]);
    }
  }
}

/**
 * Implements hook_preprocess_field().
 */
function field_swiper_preprocess_field(&$variables) {
  if ($variables['element']['#formatter'] == 'swiper_formatter') {
    $delta = 0;
    while (!empty($variables['element'][$delta])) {
      // Unset the _attributes property to prevent it from being rendered on
      // contained elements. This happens for example when using the responsive
      // image formatter of the file_entity module and prevents proper working
      // of the JS library due to nested elements with the swiper-slide class.
      unset($variables['element']['#items'][$delta]->_attributes);
      $delta++;
    }
  }
}
