# Describe the option set config entity type.
reference_swiper.swiper_option_set.*:
  type: config_entity
  label: 'Swiper option set config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    parameters:
      type: mapping
      label: 'Parameters'
      mapping:
        initialSlide:
          type: integer
          label: 'initialSlide'
        direction:
          type: string
          label: 'direction'
        speed:
          type: integer
          label: 'speed'
        setWrapperSize:
          type: boolean
          label: 'setWrapperSize'
        virtualTranslate:
          type: boolean
          label: 'virtualTranslate'
        width:
          type: integer
          label: 'width'
        height:
          type: integer
          label: 'height'
        autoHeight:
          type: boolean
          label: 'autoHeight'
        roundLengths:
          type: boolean
          label: 'roundLengths'
        nested:
          type: boolean
          label: 'nested'
        autoplay:
          type: integer
          label: 'autoplay'
        autoplayStopOnLast:
          type: boolean
          label: 'autoplayStopOnLast'
        autoplayDisableOnInteraction:
          type: boolean
          label: 'autoplayDisableOnInteraction'
        watchSlidesProgress:
          type: boolean
          label: 'watchSlidesProgress'
        watchSlidesVisibility:
          type: boolean
          label: 'watchSlidesVisibility'
        freeMode:
          type: boolean
          label: 'freeMode'
        freeModeMomentum:
          type: boolean
          label: 'freeModeMomentum'
        freeModeMomentumRatio:
          type: integer
          label: 'freeModeMomentumRatio'
        freeModeMomentumBounce:
          type: boolean
          label: 'freeModeMomentumBounce'
        freeModeMomentumBounceRatio:
          type: integer
          label: 'freeModeMomentumBounceRatio'
        freeModeMinimumVelocity:
          type: float
          label: 'freeModeMinimumVelocity'
        freeModeSticky:
          type: boolean
          label: 'freeModeSticky'
        effect:
          type: string
          label: 'effect'
        fade:
          type: string
          label: 'fade'
        cube:
          type: string
          label: 'cube'
        coverflow:
          type: string
          label: 'coverflow'
        flip:
          type: string
          label: 'flip'
#        parallax:
#          type: boolean
#          label: 'parallax'
        spaceBetween:
          type: integer
          label: 'spaceBetween'
        slidesPerView:
          type: string
          label: 'slidesPerView'
        slidesPerColumn:
          type: integer
          label: 'slidesPerColumn'
        slidesPerColumnFill:
          type: string
          label: 'slidesPerColumnFill'
        slidesPerGroup:
          type: integer
          label: 'slidesPerGroup'
        centeredSlides:
          type: boolean
          label: 'centeredSlides'
        slidesOffsetBefore:
          type: integer
          label: 'slidesOffsetBefore'
        slidesOffsetAfter:
          type: integer
          label: 'slidesOffsetAfter'
        grabCursor:
          type: boolean
          label: 'grabCursor'
        touchEventsTarget:
          type: string
          label: 'touchEventsTarget'
        touchRatio:
          type: integer
          label: 'touchRatio'
        touchAngle:
          type: integer
          label: 'touchAngle'
        simulateTouch:
          type: boolean
          label: 'simulateTouch'
        shortSwipes:
          type: boolean
          label: 'shortSwipes'
        longSwipes:
          type: boolean
          label: 'longSwipes'
        longSwipesRatio:
          type: float
          label: 'longSwipesRatio'
        longSwipesMs:
          type: integer
          label: 'longSwipesMs'
        followFinger:
          type: boolean
          label: 'followFinger'
        onlyExternal:
          type: boolean
          label: 'onlyExternal'
        threshold:
          type: integer
          label: 'threshold'
        touchMoveStopPropagation:
          type: boolean
          label: 'touchMoveStopPropagation'
        iOSEdgeSwipeDetection:
          type: boolean
          label: 'iOSEdgeSwipeDetection'
        iOSEdgeSwipeThreshold:
          type: integer
          label: 'iOSEdgeSwipeThreshold'
        resistance:
          type: boolean
          label: 'resistance'
        resistanceRatio:
          type: float
          label: 'resistanceRatio'
        preventClicks:
          type: boolean
          label: 'preventClicks'
        preventClicksPropagation:
          type: boolean
          label: 'preventClicksPropagation'
        slideToClickedSlide:
          type: boolean
          label: 'slideToClickedSlide'
        allowSwipeToPrev:
          type: boolean
          label: 'allowSwipeToPrev'
        allowSwipeToNext:
          type: boolean
          label: 'allowSwipeToNext'
        noSwiping:
          type: boolean
          label: 'noSwiping'
        noSwipingClass:
          type: string
          label: 'noSwipingClass'
        swipeHandler:
          type: string
          label: 'swipeHandler'
        uniqueNavElements:
          type: boolean
          label: 'uniqueNavElements'
        pagination:
          type: string
          label: 'pagination'
        paginationType:
          type: string
          label: 'paginationType'
        paginationHide:
          type: boolean
          label: 'paginationHide'
        paginationClickable:
          type: boolean
          label: 'paginationClickable'
        paginationElement:
          type: string
          label: 'paginationElement'
        paginationBulletRender(index, className):
          type: string
          label: 'paginationBulletRender(index, className)'
        paginationFractionRender(swiper, currentClassName, totalClassName):
          type: string
          label: 'paginationFractionRender(swiper, currentClassName, totalClassName)'
        paginationProgressRender(swiper, progressbarClass):
          type: string
          label: 'paginationProgressRender(swiper, progressbarClass)'
        paginationCustomRender(swiper, current, total):
          type: string
          label: 'paginationCustomRender(swiper, current, total)'
        nextButton:
          type: string
          label: 'nextButton'
        prevButton:
          type: string
          label: 'prevButton'
        scrollbar:
          type: string
          label: 'scrollbar'
        scrollbarHide:
          type: boolean
          label: 'scrollbarHide'
        scrollbarDraggable:
          type: boolean
          label: 'scrollbarDraggable'
        scrollbarSnapOnRelease:
          type: boolean
          label: 'scrollbarSnapOnRelease'
        a11y:
          type: boolean
          label: 'a11y'
        prevSlideMessage:
          type: string
          label: 'prevSlideMessage'
        nextSlideMessage:
          type: string
          label: 'nextSlideMessage'
        firstSlideMessage:
          type: string
          label: 'firstSlideMessage'
        lastSlideMessage:
          type: string
          label: 'lastSlideMessage'
        paginationBulletMessage:
          type: string
          label: 'paginationBulletMessage'
        keyboardControl:
          type: boolean
          label: 'keyboardControl'
        mousewheelControl:
          type: boolean
          label: 'mousewheelControl'
        mousewheelForceToAxis:
          type: boolean
          label: 'mousewheelForceToAxis'
        mousewheelReleaseOnEdges:
          type: boolean
          label: 'mousewheelReleaseOnEdges'
        mousewheelInvert:
          type: boolean
          label: 'mousewheelInvert'
        mousewheelSensitivity:
          type: integer
          label: 'mousewheelSensitivity'
        hashnav:
          type: boolean
          label: 'hashnav'
        preloadImages:
          type: boolean
          label: 'preloadImages'
        updateOnImagesReady:
          type: boolean
          label: 'updateOnImagesReady'
#        lazyLoading:
#          type: boolean
#          label: 'lazyLoading'
#        lazyLoadingInPrevNext:
#          type: boolean
#          label: 'lazyLoadingInPrevNext'
#        lazyLoadingInPrevNextAmount:
#          type: integer
#          label: 'lazyLoadingInPrevNextAmount'
#        lazyLoadingOnTransitionStart:
#          type: boolean
#          label: 'lazyLoadingOnTransitionStart'
        loop:
          type: boolean
          label: 'loop'
        loopAdditionalSlides:
          type: integer
          label: 'loopAdditionalSlides'
        loopedSlides:
          type: integer
          label: 'loopedSlides'
#        control:
#          type: string
#          label: 'control'
        controlInverse:
          type: boolean
          label: 'controlInverse'
        controlBy:
          type: string
          label: 'controlBy'
        observer:
          type: boolean
          label: 'observer'
        observeParents:
          type: boolean
          label: 'observeParents'
        breakpoints:
          type: string
          label: 'breakpoints'
        runCallbacksOnInit:
          type: boolean
          label: 'runCallbacksOnInit'
        onInit:
          type: string
          label: 'onInit(swiper)'
        onSlideChangeStart:
          type: string
          label: 'onSlideChangeStart(swiper)'
        onSlideChangeEnd:
          type: string
          label: 'onSlideChangeEnd(swiper)'
        onSlideNextStart:
          type: string
          label: 'onSlideNextStart(swiper)'
        onSlideNextEnd:
          type: string
          label: 'onSlideNextEnd(swiper)'
        onSlidePrevStart:
          type: string
          label: 'onSlidePrevStart(swiper)'
        onSlidePrevEnd:
          type: string
          label: 'onSlidePrevEnd(swiper)'
        onTransitionStart:
          type: string
          label: 'onTransitionStart(swiper)'
        onTransitionEnd:
          type: string
          label: 'onTransitionEnd(swiper)'
        onTouchStart:
          type: string
          label: 'onTouchStart(swiper, event)'
        onTouchMove:
          type: string
          label: 'onTouchMove(swiper, event)'
        onTouchMoveOpposite:
          type: string
          label: 'onTouchMoveOpposite(swiper, event)'
        onSliderMove:
          type: string
          label: 'onSliderMove(swiper, event)'
        onTouchEnd:
          type: string
          label: 'onTouchEnd(swiper, event)'
        onClick:
          type: string
          label: 'onClick(swiper, event)'
        onTap:
          type: string
          label: 'onTap(swiper, event)'
        onDoubleTap:
          type: string
          label: 'onDoubleTap(swiper, event)'
        onImagesReady:
          type: string
          label: 'onImagesReady(swiper)'
        onProgress:
          type: string
          label: 'onProgress(swiper, progress)'
        onReachBeginning:
          type: string
          label: 'onReachBeginning(swiper)'
        onReachEnd:
          type: string
          label: 'onReachEnd(swiper)'
        onDestroy:
          type: string
          label: 'onDestroy(swiper)'
        onSetTranslate:
          type: string
          label: 'onSetTranslate(swiper, translate)'
        onSetTransition:
          type: string
          label: 'onSetTransition(swiper, transition)'
        onAutoplay:
          type: string
          label: 'onAutoplay(swiper)'
        onAutoplayStart:
          type: string
          label: 'onAutoplayStart(swiper)'
        onAutoplayStop:
          type: string
          label: 'onAutoplayStop(swiper)'
#        onLazyImageLoad:
#          type: string
#          label: 'onLazyImageLoad(swiper, slide, image)'
#        onLazyImageReady:
#          type: string
#          label: 'onLazyImageReady(swiper, slide, image)'
        onPaginationRendered:
          type: string
          label: 'onPaginationRendered(swiper, paginationContainer)'
        slideClass:
          type: string
          label: 'slideClass'
        slideActiveClass:
          type: string
          label: 'slideActiveClass'
        slideVisibleClass:
          type: string
          label: 'slideVisibleClass'
        slideDuplicateClass:
          type: string
          label: 'slideDuplicateClass'
        slideNextClass:
          type: string
          label: 'slideNextClass'
        slidePrevClass:
          type: string
          label: 'slidePrevClass'
        wrapperClass:
          type: string
          label: 'wrapperClass'
        bulletClass:
          type: string
          label: 'bulletClass'
        bulletActiveClass:
          type: string
          label: 'bulletActiveClass'
        paginationHiddenClass:
          type: string
          label: 'paginationHiddenClass'
        paginationCurrentClass:
          type: string
          label: 'paginationCurrentClass'
        paginationTotalClass:
          type: string
          label: 'paginationTotalClass'
        paginationProgressbarClass:
          type: string
          label: 'paginationProgressbarClass'
        buttonDisabledClass:
          type: string
          label: 'buttonDisabledClass'
